spring:
  application:
    name: microservice-spring-security-basic

# Database Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/securityDB
    username: root
    password: pass

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

# Security config
#  security:
#    user:
#      name: root
#      password: root

  #SecretKeyForSpringSecurityCourse
  security:
    jwt:
      key:
        private: d98b2777e33847054692ee4ebd60f3f4bc14e5dccfca670c2c1a4c059f89435a
      user:
        generator: root-jwt