spring:
  application:
    name: microservice-spring-security-basic

# Database Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/securityDB
    username: root
    password: pass

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

# Security config
#  security:
#    user:
#      name: root
#      password: root